### ISSUE TITLE
Should menu items have tooltips?

### ISSUE THREAD

**Issue by qdot** [qdot/systray-rs#14]
On linux, at least, this could be a thing. I'm not sure whether it'd be a /good/ thing, but it could totally be a thing.

**Comment by jonhoo** [comment]
To me personally this is not all that important :p

**Comment by daniel-abramov** [comment]
It seems that on Mac such possibility does not exist. There are no tooltips for other applications (including system ones). And judging from the official documentation, the tooltip property is deprecated (https://developer.apple.com/reference/appkit/nsstatusitem), the configuration for the tray icon itself has to be done via `button` property which basically is a `NSButton`.

**Comment by qdot** [comment]
Yeah, just checked on my mac, the only thing that pops a tooltip on mouseover is Dropbox, and they're probably doing something special to pull that off. Gonna WONTFIX this at least, as I think tooltip per menu item would probably get silly fast.
