### ISSUE TITLE
Remove winapipatch.rs when winapi 0.3 lands

### ISSUE THREAD

**Issue by qdot** [qdot/systray-rs#16]
Most if not all of the symbols we need are already in winapi 0.3. Until that publishes to crates.io, we're stuck using our winapipatch.rs file. This is a reminder bug to clean that up once it happens.

**Comment by jonhoo** [comment]
Or just add a `git` dependency for now? If you're already doing that for Linux support, I'd just clean this up straight-away too.

**Comment by qdot** [comment]
Huh. For some reason I was under the impression that git dependencies weren't allowed in crates. I'll fix that, thanks!

**Comment by jonhoo** [comment]
Git dependencies are allowed, but you can't then upload the crate to crates.io.

**Comment by qdot** [comment]
Ok, well, we'll just have a few branches then. Will probably keep master as head of development, with git repo dependencies for what we need, can take feature branches off of that. Will make a "crate" branch for code we can actually submit to crates.io for the moment, which will go away once winapi 0.3 and the linux gtk stuff are usable off crates.io. Tags will point to the crate branch until we can bring everything back together, since versioning against the main package repo is probably best.

Yay project management. :|

**Comment by qdot** [comment]
Done in 0.4.0
