### ISSUE TITLE
Add a crate?

### ISSUE THREAD

**Issue by vext01** [qdot/systray-rs#2]
Hi,

Any chance this will make it to crates.io?

Thanks

**Comment by qdot** [comment]
Yeah, that's the plan. Unfortunately right now it depends on a lot of additions to winapi-rs that, at the time I was last working on this, were going to be delayed until their 0.3 release. I'll check in with them and see what the status is on that, and if I can integrate my changes before that, hopefully we can get a crate going.

**Comment by daniel-abramov** [comment]
I've noticed that your fork of winapi-rs contains some changes which are not present in ws-rs? Do you plan to adapt them to the 0.3 new order and make a pull request? Without them the systray-rs will not work I guess.

**Comment by qdot** [comment]
Ok, we actually have a crate now!

https://crates.io/crates/systray

I ended up bringing my patches for winapi-rs 0.3 into the windows module of systray-rs for right now, as well as copying over a couple of macros. I /really/ don't like this, but I also don't want to sit here stuck until winapi-rs decides to update crates.

I'll still be putting in patches to winapi-rs, and will be removing all of this grossness once those actually get released.
