### ISSUE TITLE
Should this project be moved to an org?

### ISSUE THREAD

**Issue by qdot** [qdot/systray-rs#25]
I keep saying I'm going to get back to working on this, and then I keep not having time. It might be good to have this project, plus libappindicator-rs/-sys handled under an org so multiple people could manage PRs and releases?

cc @application-developer-DA

**Comment by daniel-abramov** [comment]
I don't have a strong opinion on that at the moment. But in case if you transfer the ownership to the organization, who will be the official maintainer then? :)

Currently it's not clear for me if `systray-rs` can become a crossplatform tray icon library, I need some time to realize if it is possible to do, without having too many OS-dependant limitations and restrictions in public interfaces.

The thing is that using libraries like `libappindicator-rs` may be simpler than using `trayicon-rs` for Linux. For Mac dealing with icons is also simple (apart from all those tricky casts to make callbacks and menus work).

**Comment by f4bio** [comment]
As stated in #33, I am currently (and hopefully in the future) more then willing to maintain this project - and probably the other ones mentioned as well.
I think an github organization would be useful as well - because why not?

**Comment by gentoo90** [comment]
If no one's willing to create an organization, then maybe it could be added to the [Rust Unofficial](https://github.com/rust-unofficial/about) organization?

**Comment by qdot** [comment]
Good news is, I'm back to writing a *lot* of rust now (https://github.com/buttplugio/buttplug-rs), so there's a chance this could get some updates again. I can at least get back to accepting PRs.

Main holdup right now is that libappindicator and bindgen have changed quite a bit since I wrote this 3 years ago, so trying to bring the dependencies up to date first has been a challenge.

**Comment by qdot** [comment]
I'm gonna go ahead and close this since I'm hopefully taking care of this again now. libappindicator has been updated, I'll be bringing in Rust 2018 reformatting this weekend, and probably releasing 0.4 within the next few weeks.
