### ISSUE TITLE
Path Resources Should Be Added To Repo

### ISSUE THREAD

**Issue by mrcbax** [qdot/systray-rs#3]
For example in `Cargo.toml` where you have the dependency line:

`winapi={ path = "../winapi-rs/" }`

Rewrite it to match:

`winapi={ path = "winapi-rs/" }`

Then put the local winapi folder inside the repository so that we can at least have a chance at compiling your code.

**Comment by qdot** [comment]
Will do. Sorry, this project was making a lot of headway then got cut off due to life getting in the way. Hoping to get back to it soon. :)
