### ISSUE TITLE
docs.rs fails to build for systray 0.4.0

### ISSUE THREAD

**Issue by PonasKovas** [qdot/systray-rs#36]
https://docs.rs/crate/systray/0.3.0

Is this project dead?

**Comment by qdot** [comment]
Ok, looks like docs.rs building is still a problem on 0.4.0, due to the special requirements of the libappindicator library. I need to make a "docs" feature that would just build the generic API portions.

**Comment by jonhoo** [comment]
Alternatively you can ask the docsrs people (on Discord) whether they could add `libappindicator` to the VM that builds the docs. They're pretty helpful with stuff like that generally!

**Comment by cdepillabout** [comment]
If you go to docs.rs for [systray-0.4.0](https://docs.rs/crate/systray/0.4.0), you can find a build log for the failed 0.4.0 build:

https://docs.rs/crate/systray/0.4.0/builds/221996

At the bottom of this page, there is a link to [open an issue](https://github.com/rust-lang/docs.rs/issues/new/choose) in case of a build failure.

 If you try to open an issue, you are presented with this comment:

> If you need a system dependency added for your crate to build, consider making a PR to https://github.com/rust-lang/crates-build-env instead of opening an issue here. There are detailed instructions for this at https://forge.rust-lang.org/docs-rs/add-dependencies.html.

It looks like this is probably the way to go.

I would be pretty happy if there were docs for systray available!

**Comment by retep998** [comment]
Perhaps you could also set Windows as the default target, since that has no dependencies on third party C libraries, just `winapi`. If the primary target fails to build then docs.rs won't build any docs for *any* target.

**Comment by Ciantic** [comment]
If windows target is all that is required, it could be done by just adding this to Cargo.toml

```
[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"
```

**Comment by jyn514** [comment]
Fixed by https://github.com/rust-lang/crates-build-env/pull/59. I queued a rebuild so you don't have to publish a new release :) https://docs.rs/crate/systray/0.4.0

**Comment by qdot** [comment]
@jyn514 Thanks! 👍
